-- Explore All objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES;



-- Explore all columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS;


-- Explore all the countries customers come from 
SELECT DISTINCT
country
FROM gold.dim_customers;

-- Explore all Product Categories 
SELECT DISTINCT
category,
subcategory,
product_name
FROM gold.dim_products
ORDER BY 1,2,3;

-- Identify the earliest and latest dates(boundaries)
-- Understand the scope of data and the timespan.

-- Find the date of the first and last order
-- How many months of Sales are available
SELECT
MIN(order_date) first_order,
MAX(order_date) last_order,
DATEDIFF(MONTH,MIN(order_date),MAX(order_date)) order_range_months
FROM gold.fact_sales;

-- Find the youngest and the oldest customer
SELECT
customer_id,
customer_key,
first_name,
last_name,
birthdate,
DATEDIFF(YEAR,birthdate,GETDATE()) age
FROM gold.dim_customers
WHERE birthdate = (SELECT MIN(birthdate) FROM gold.dim_customers) OR birthdate = (SELECT MAX(birthdate) FROM gold.dim_customers)
ORDER BY birthdate;

-- Measure Exploration
-- Find the total Sales
SELECT
SUM(sales_amount) total_sales
FROM gold.fact_sales;

-- Find how many items are sold
SELECT
SUM(quantity) total_items_sold
FROM gold.fact_sales;

-- Find the average selling price
SELECT
AVG(price) avg_selling_price
FROM gold.fact_sales;

-- Find the total number of orders
SELECT 
COUNT(DISTINCT order_number) total_orders
FROM gold.fact_sales;

-- Find the total number of products
SELECT 
COUNT(DISTINCT product_name) total_products
FROM gold.dim_products;

-- Find the total number of customers
SELECT
COUNT(customer_key) total_customers
FROM gold.dim_customers;

-- Find the total number of customers that has placed an order
SELECT
COUNT(DISTINCT customer_key) total_customers_with_orders
FROM gold.fact_sales;

-- Generate a report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name,SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name,SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Averge Selling price' AS measure_name,AVG(price) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Orders' AS measure_name,COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products' AS measure_name,COUNT(DISTINCT product_name) AS measure_value FROM gold.dim_products
UNION ALL
SELECT 'Total Nr. customers' AS measure_name,COUNT(customer_key) AS measure_value FROM gold.dim_customers
UNION ALL
SELECT 'Total Nr. customers with Orders' AS measure_name,COUNT(DISTINCT customer_key) AS measure_value FROM gold.fact_sales


-- MAGNITUDE ANALYSIS

-- Find the total customers by countries
SELECT
country,
COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
gender,
COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
category,
COUNT(product_key) total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
category,
AVG(cost) average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;

-- What is the total revenue generated for each category?
SELECT
p.category,
SUM(s.sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Find total revenue generated by each cutsomer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries ? (total quantity by country)
SELECT
c.country,
SUM(s.quantity) total_sold_items
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;

-- RANKING ANALYSIS

-- Which 5 products generate the highest revenue?
SELECT TOP 5
p.product_key,
p.product_name,
SUM(s.sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_key,
p.product_name
ORDER BY total_revenue DESC;

-- What are the 5 worst performing products in terms of sales ?
SELECT TOP 5
p.product_key,
p.product_name,
SUM(s.sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_key,
p.product_name
ORDER BY total_revenue;

-- Find the top 10 customers who have generated the highest revenue 
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC;

-- The 3 customers with the fewest orders placed
SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT s.order_number) total_orders
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name
ORDER BY total_orders;
